"""added new column in product model

Revision ID: 087065f65a8f
Revises: d7caaf72e21c
Create Date: 2023-05-02 00:40:59.950426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087065f65a8f'
down_revision = 'd7caaf72e21c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_histories', sa.Column('price_for_sale', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_histories', 'price_for_sale')
    # ### end Alembic commands ###
