"""initial

Revision ID: 0a54338a1e7c
Revises: 
Create Date: 2023-04-14 23:38:37.464252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a54338a1e7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('product_nm_id', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('api_token_standard', sa.String(), nullable=True),
    sa.Column('api_token_advertisement', sa.String(), nullable=True),
    sa.Column('api_token_statistic', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderUid', sa.String(), nullable=True),
    sa.Column('nm_id', sa.BIGINT(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.BIGINT(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('shops_supplier', sa.String(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.BIGINT(), nullable=True),
    sa.Column('vendor_code', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('subj_name', sa.String(), nullable=True),
    sa.Column('subj_root_name', sa.String(), nullable=True),
    sa.Column('imt_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priceU', sa.Integer(), nullable=True),
    sa.Column('salePriceU', sa.Integer(), nullable=True),
    sa.Column('clientSale', sa.Integer(), nullable=True),
    sa.Column('basicSale', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('shops_supplier', sa.String(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('product_histories')
    op.drop_table('orders')
    op.drop_table('shops')
    op.drop_table('characteristics')
    # ### end Alembic commands ###
