"""added new column

Revision ID: 315a0e070ab8
Revises: 0a54338a1e7c
Create Date: 2023-04-15 16:47:27.502733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315a0e070ab8'
down_revision = '0a54338a1e7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
