"""added new column in product model

Revision ID: d7caaf72e21c
Revises: 315a0e070ab8
Create Date: 2023-05-02 00:38:19.098561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7caaf72e21c'
down_revision = '315a0e070ab8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price_for_sale', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'price_for_sale')
    # ### end Alembic commands ###
